application: citygoround
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
  
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /(.*)
  script: bootstrap.py
